# -*- coding: utf-8 -*-
"""new_cnn_4996.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIBdN3o40N5Z61S7qNcmoTyFiS6bfCmI
"""

# Commented out IPython magic to ensure Python compatibility.

# %pip install tensorflow==2.10

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

def build_keras_cnn():
    model = keras.Sequential([
        # Conv1: 1 input channel -> 8 filters, 3x3 kernel
        layers.Conv2D(8, (3,3), activation='relu', input_shape=(28,28,1), name="conv1"),
        layers.MaxPooling2D((2,2)),

        # Conv2: 8 -> 10 filters, 3x3 kernel
        layers.Conv2D(10, (3,3), activation='relu', name="conv2"),
        layers.MaxPooling2D((2,2)),

        # Flatten
        layers.Flatten(),

        # FC1: 250 -> 16
        layers.Dense(16, activation='relu', name="fc1"),

        # FC2: 16 -> 10
        layers.Dense(10, activation='softmax', name="fc2")
    ])

    # same loss/optimizer setup as PyTorch (NLLLoss ↔ categorical crossentropy)
    model.compile(
        optimizer=keras.optimizers.SGD(learning_rate=0.01, momentum=0.9),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return model

# Instantiate
keras_model = build_keras_cnn()
keras_model.summary()

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Normalize & expand dims for channel
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0
x_train = x_train[..., None]   # (N,28,28,1)
x_test = x_test[..., None]

keras_model.fit(x_train, y_train, batch_size=64, epochs=15, validation_data=(x_test, y_test))

# Save model
keras_model.save("mnist_cnn.h5")

# Save model
keras_model.save("mnist_cnn.h5")