import os

def generate_systolic_array(N):
    filename = f"ws_sa_{N}x{N}.sv"
    
    with open(filename, 'w') as f:
        # ==========================================
        # 1. HEADER & PORTS
        # ==========================================
        f.write(f"// ====================================================\n")
        f.write(f"// Auto-generated {N}x{N} Weight-Stationary Systolic Array\n")
        f.write(f"// Generated by Python Script\n")
        f.write(f"// ====================================================\n")
        f.write(f"`timescale 1ns / 1ps\n\n")
        
        f.write(f"module ws_sa_{N}x{N} #(\n")
        f.write(f"    parameter int DATA_WIDTH = 17,\n")
        f.write(f"    parameter int PSUM_WIDTH = (2 * DATA_WIDTH) + 8,\n")
        f.write(f"    parameter int SIZE       = {N}\n")
        f.write(f") (\n")
        f.write(f"    input logic clk,\n")
        f.write(f"    input logic rst_n,\n\n")
        
        f.write(f"    // Weights In\n")
        f.write(f"    input logic [(DATA_WIDTH*SIZE)-1:0] wgt_flatten_i,\n")
        f.write(f"    input logic wgt_load_i,\n\n")
        
        f.write(f"    // Activations In\n")
        f.write(f"    input logic [(DATA_WIDTH*SIZE)-1:0] act_flatten_i,\n")
        f.write(f"    input logic [SIZE-1:0] act_valid_i,\n\n")
        
        f.write(f"    // Partial Sums Out\n")
        f.write(f"    output logic [(PSUM_WIDTH*SIZE)-1:0] psum_flatten_o,\n")
        f.write(f"    output logic [SIZE-1:0] psum_valid_o\n")
        f.write(f");\n\n")

        # ==========================================
        # 2. INPUT UNPACKING (Tách dây gộp thành dây lẻ)
        # ==========================================
        f.write("    // ==========================================\n")
        f.write("    // Input Unpacking\n")
        f.write("    // ==========================================\n")
        for r in range(N):
            f.write(f"    logic signed [DATA_WIDTH-1:0] act_row{r}_i;\n")
            f.write(f"    assign act_row{r}_i = act_flatten_i[({r}*DATA_WIDTH)+:DATA_WIDTH];\n")
        f.write("\n")
        for c in range(N):
            f.write(f"    logic signed [DATA_WIDTH-1:0] wgt_col{c}_i;\n")
            f.write(f"    assign wgt_col{c}_i = wgt_flatten_i[({c}*DATA_WIDTH)+:DATA_WIDTH];\n")
        f.write("\n")

        # ==========================================
        # 3. INTERNAL WIRES (Khai báo hàng ngàn dây nối chéo)
        # ==========================================
        f.write("    // ==========================================\n")
        f.write("    // Internal Routing Wires\n")
        f.write("    // ==========================================\n")
        for r in range(N):
            for c in range(N):
                # Dây Activations (Ngang)
                if c < N - 1:
                    f.write(f"    logic signed [DATA_WIDTH-1:0] act_{r}_{c}_to_{r}_{c+1};\n")
                    f.write(f"    logic act_v_{r}_{c}_to_{r}_{c+1};\n")
                # Dây Weights (Dọc)
                if r < N - 1:
                    f.write(f"    logic signed [DATA_WIDTH-1:0] wgt_{r}_{c}_to_{r+1}_{c};\n")
                # Dây Psums (Dọc)
                if r < N - 1:
                    f.write(f"    logic signed [PSUM_WIDTH-1:0] psum_{r}_{c}_to_{r+1}_{c};\n")
                    f.write(f"    logic psum_v_{r}_{c}_to_{r+1}_{c};\n")
                else:
                    f.write(f"    logic signed [PSUM_WIDTH-1:0] psum_{r}_{c}_out;\n")
                    f.write(f"    logic psum_v_{r}_{c}_out;\n")
        f.write("\n")

        # ==========================================
        # 4. OUTPUT PACKING (Gộp kết quả trả về Testbench)
        # ==========================================
        f.write("    // ==========================================\n")
        f.write("    // Output Packing\n")
        f.write("    // ==========================================\n")
        for c in range(N):
            f.write(f"    assign psum_flatten_o[({c}*PSUM_WIDTH)+:PSUM_WIDTH] = psum_{N-1}_{c}_out;\n")
            f.write(f"    assign psum_valid_o[{c}] = psum_v_{N-1}_{c}_out;\n")
        f.write("\n")

        # ==========================================
        # 5. PE INSTANTIATION (Khởi tạo N*N khối PE)
        # ==========================================
        f.write("    // ==========================================\n")
        f.write("    // PE Array Instantiation\n")
        f.write("    // ==========================================\n")
        for r in range(N):
            f.write(f"    // ---------------- ROW {r} ----------------\n")
            for c in range(N):
                f.write(f"    pe #(\n")
                f.write(f"        .DATA_WIDTH(DATA_WIDTH),\n")
                f.write(f"        .PSUM_WIDTH(PSUM_WIDTH)\n")
                f.write(f"    ) pe_{r}_{c} (\n")
                f.write(f"        .clk(clk),\n")
                f.write(f"        .rst_n(rst_n),\n\n")

                # Nối dây Activation In
                act_i = f"act_row{r}_i" if c == 0 else f"act_{r}_{c-1}_to_{r}_{c}"
                act_v_i = f"act_valid_i[{r}]" if c == 0 else f"act_v_{r}_{c-1}_to_{r}_{c}"
                f.write(f"        .act_i({act_i}),\n")
                f.write(f"        .act_valid_i({act_v_i}),\n")

                # Nối dây Activation Out
                act_o = "" if c == N - 1 else f"act_{r}_{c}_to_{r}_{c+1}"
                act_v_o = "" if c == N - 1 else f"act_v_{r}_{c}_to_{r}_{c+1}"
                f.write(f"        .act_o({act_o}),\n")
                f.write(f"        .act_valid_o({act_v_o}),\n\n")

                # Nối dây Psum In
                psum_i = "'0" if r == 0 else f"psum_{r-1}_{c}_to_{r}_{c}"
                psum_v_i = "1'b1" if r == 0 else f"psum_v_{r-1}_{c}_to_{r}_{c}"
                f.write(f"        .psum_i({psum_i}),\n")
                f.write(f"        .psum_valid_i({psum_v_i}),\n")

                # Nối dây Psum Out
                psum_o = f"psum_{r}_{c}_out" if r == N - 1 else f"psum_{r}_{c}_to_{r+1}_{c}"
                psum_v_o = f"psum_v_{r}_{c}_out" if r == N - 1 else f"psum_v_{r}_{c}_to_{r+1}_{c}"
                f.write(f"        .psum_o({psum_o}),\n")
                f.write(f"        .psum_valid_o({psum_v_o}),\n\n")

                # Nối dây Weight In
                wgt_i = f"wgt_col{c}_i" if r == 0 else f"wgt_{r-1}_{c}_to_{r}_{c}"
                f.write(f"        .weight_i({wgt_i}),\n")
                f.write(f"        .weight_load_i(wgt_load_i),\n")

                # Nối dây Weight Out
                wgt_o = "" if r == N - 1 else f"wgt_{r}_{c}_to_{r+1}_{c}"
                f.write(f"        .weight_o({wgt_o})\n")

                f.write(f"    );\n\n")

        f.write("endmodule\n")
    print(f">>> Success: Generated {filename} with {N*N} PE blocks!")

# ==========================================
# CẤU HÌNH KÍCH THƯỚC MẢNG Ở ĐÂY
# ==========================================
if __name__ == "__main__":
    # Đổi số này thành bất kỳ kích thước nào bạn muốn (3, 4, 16, 64,...)
    TARGET_N = 64
    generate_systolic_array(TARGET_N)